# Generated by Django 3.2.2 on 2021-05-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('acctividad', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='tarotistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('especialidades', models.CharField(max_length=500)),
                ('actividades', models.CharField(max_length=500)),
            ],
        ),
    ]
